# Install lldp
- src: giovtorres.lldpad

# Install bastion
- src: epcjr.ansible_role_bastion

# Install perfsonar roles
- src: https://github.com/perfsonar/ansible-role-perfsonar-testpoint
- src: https://github.com/perfsonar/ansible-role-perfsonar-toolkit
- src: https://github.com/epcjr/ansible-role-perfsonar-psconfig-publisher
- src: https://github.com/epcjr/ansible-role-perfsonar-archive
- src: https://github.com/epcjr/ansible-role-perfsonar-installer
#- src: https://github.com/epcjr/ansible-role-perfsonar-psconfig
#- src: https://github.com/perfsonar/ansible-role-perfsonar-psconfig
