---
# handlers file for perfsonar-testpoint

- name: restart ntp
  service:
    name: "{{ ntp_service }}"
    state: restarted

- name: restart ssh
  service:
    name: "{{ ssh_service }}"
    state: restarted

