---
- name: Install lldpad
  package:
    name: lldpad
    state: present

- name: Start lldpad service for lldptool commands
  service:
    name: lldpad
    enabled: yes
    state: started

- name: Initialize an empty list for active interfaces
  set_fact:
    active_interfaces: []

- name: Get list of active interfaces
  set_fact:
    active_interfaces: "{{ active_interfaces }} + [ '{{ item }}' ]"
  when:
    - "'bond' not in item"
    - "'team' not in item"
    - hostvars[inventory_hostname]['ansible_' + item]['type'] == 'ether'
    - hostvars[inventory_hostname]['ansible_' + item]['active']
    - lldpad_active_interfaces
  with_items:
    - "{{ ansible_interfaces | map('replace', '-', '_') | list }}"

- name: Use explicit list of interfaces
  set_fact:
    active_interfaces: "{{ lldpad_selected_interfaces }}"
  when:
    - not lldpad_active_interfaces
    - lldpad_selected_interfaces

- name: Get LLDP adminstatus for all active interfaces
  command: "/usr/sbin/lldptool get-lldp -i {{ item }} adminStatus"
  changed_when: False
  with_items: "{{ active_interfaces }}"
  register: lldp_adminStatus

- name: Enable LLDP adminstatus for all active interfaces
  command: "/usr/sbin/lldptool set-lldp -i {{ item.item }} adminStatus=rxtx"
  with_items: "{{ lldp_adminStatus.results }}"
  when: item.stdout != "adminStatus=rxtx"
  notify:
    - restart lldpad

- name: Get LLDP sysName tlv for all active interfaces
  command: "/usr/sbin/lldptool get-tlv -i {{ item }} -V sysName -c enableTx"
  changed_when: False
  with_items: "{{ active_interfaces }}"
  register: lldp_sysName

- name: Enable LLDP sysName tlv for all active interfaces
  command: "/usr/sbin/lldptool set-tlv -i {{ item.item }} -V sysName enableTx=yes"
  with_items: "{{ lldp_sysName.results }}"
  when: item.stdout != "enableTx=yes"
  notify:
    - restart lldpad

- name: Get LLDP portDesc tlv for all active interfaces
  command: "/usr/sbin/lldptool get-tlv -i {{ item }} -V portDesc -c enableTx"
  changed_when: False
  with_items: "{{ active_interfaces }}"
  register: lldp_portDesc

- name: Enable LLDP portDesc tlv for all active interfaces
  command: "/usr/sbin/lldptool set-tlv -i {{ item.item }} -V portDesc enableTx=yes"
  with_items: "{{ lldp_portDesc.results }}"
  when: item.stdout != "enableTx=yes"
  notify:
    - restart lldpad
